### ISSUE TITLE
error with title containing ' (single quote)

### ISSUE THREAD

**Issue by kaese** [mariusknaust/spotlight#14]
Tried to get a new picture but it fails:

$  ./spotlight.sh 
expected end of input:
  'file:///home/foo/.local/share/backgrounds/23-05-09-08-32-04-Grant's gazelles (grant's gazelle).jpg'
                                                                       ^                                
expected end of input:
  'file:///home/foo/.local/share/backgrounds/23-05-09-08-32-04-Grant's gazelles (grant's gazelle).jpg'
                                                                       ^                                
$ 

^ is pointing to "s" in "Grant's". I don't have time to debug the issue right now, so I'm reporting it.

**Comment by mariusknaust** [comment]
Thanks for reporting!
