### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by jans23** [mariusknaust/spotlight#6]
Cool project. Could you give a few hints how to install it on Ubuntu Linux, please?

**Comment by mariusknaust** [comment]
Thanks! I’ve just added an [installation section](https://github.com/mariusknaust/spotlight/blob/master/README.md#installation) to the readme, I hope it will help you.

**Comment by jans23** [comment]
Thanks. I followed the instructions and it looks good:
```
$ systemctl --user enable spotlight.timer
Created symlink /home/me/.config/systemd/user/default.target.wants/spotlight.timer → /home/me/.local/share/systemd/user/spotlight.timer.
```
But my desktop background didn't change. What to do?

**Comment by mariusknaust** [comment]
It will change daily now that you have enabled it, until you disable the timer again by running `systemctl --user disable spotlight.timer`.

To trigger it once you can either use the desktop entry by looking for _spotlight_ in your gnome app menu, run `spotlight.sh` in a terminal, or trigger the service manually with `systemctl --user start spotlight.service`.

**Comment by jans23** [comment]
I installed it the "local" way, as described in the installation documentation. Executing spotlight.sh manually does change the background successfully. But the following doesn't work:
```
$ systemctl --user start spotlight.service
Failed to start spotlight.service: Unit spotlight.service not found.
```

**Comment by jans23** [comment]
> It will change daily now that you have enabled it, until you disable the timer again by running systemctl --user disable spotlight.timer.
> 
> To trigger it once you can either use the desktop entry by looking for spotlight in your gnome app menu, run spotlight.sh in a terminal, or trigger the service manually with systemctl --user start spotlight.service.

Perhaps it would be good to add this information to the README.

**Comment by mariusknaust** [comment]
> > It will change daily now that you have enabled it, until you disable the timer again by running systemctl --user disable spotlight.timer.
> > To trigger it once you can either use the desktop entry by looking for spotlight in your gnome app menu, run spotlight.sh in a terminal, or trigger the service manually with systemctl --user start spotlight.service.
> 
> Perhaps it would be good to add this information to the README.

I already did that yesterday :)

**Comment by mariusknaust** [comment]
> I installed it the "local" way, as described in the installation documentation. Executing spotlight.sh manually does change the background successfully. But the following doesn't work:
> 
> ```
> $ systemctl --user start spotlight.service
> Failed to start spotlight.service: Unit spotlight.service not found.
> ```

And I guess consequently the daily change doesn't work? Weird, because you could enable the timer. Can you verify that the service is in the same directory as the timer. I will try to reproduce it later.

**Comment by jans23** [comment]
> Can you verify that the service is in the same directory as the timer.

Confirmed.

**Comment by mariusknaust** [comment]
I just removed my package and did the local installation and it worked.

**Comment by jans23** [comment]
After a day the wallpaper did changed successfully. Still the error above happens when executing manually.

I noticed that the wallpaper on the locked screen is different from the wallpaper on the (logged in) desktop (both are from Microsoft). Is this expected?

**Comment by mariusknaust** [comment]
Weird, because the timer is using the service as well.

Indeed, that is expected behavior.

**Comment by jans23** [comment]
Since installation a few days ago, the wallpaper didn't change. What to do?

**Comment by mariusknaust** [comment]
Did you had a look at the log yet, e.g `systemctl --user status spotlight.timer` or `systemctl --user status spotlight.service`?

**Comment by jans23** [comment]
```
$ systemctl --user status spotlight.timer
Unit spotlight.timer could not be found.
$ systemctl --user status spotlight.service
Unit spotlight.service could not be found.
```

**Comment by mariusknaust** [comment]
Maybe the paths are different on Ubuntu? But couldn't you enable the timer and haven't you reported that it once changed?

**Comment by jans23** [comment]
Enabling the timer succeeded but starting the timer doesn't.

**Comment by mariusknaust** [comment]
#7 might fix your problem, can you try the latest version?

**Comment by jans23** [comment]
Unfortunately it doesn't fix this issue.

**Comment by CodeFinder2** [comment]
I can confirm, `spotlight.sh` is working properly on Ubuntu 20.04 LTS (64 bit)! Nice work! :-)

**Comment by mariusknaust** [comment]
Thanks for the confirmation, @CodeFinder2!
